#!/bin/bash -e

if getent passwd whattodo > /dev/null 2>&1; then
  echo "Nothing to do" > /dev/null 2>&1
else
  useradd -rmU -d /var/lib/whattodo whattodo
  chown :root /var/lib/whattodo
  chmod 770 /var/lib/whattodo
fi
