if(${WIN32})
  if(${GLOBAL_INSTALL})
    set(CMAKE_INSTALL_PREFIX "$ENV{ProgramFiles}/${PROJECT_NAME}")
  else()
    set(CMAKE_INSTALL_PREFIX ${CMAKE_SOURCE_DIR}/windows)
  endif()
else()
  if(${GLOBAL_INSTALL})
    set(CMAKE_INSTALL_PREFIX "/opt/${PROJECT_NAME}")
  else()
    set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/linux")
  endif()
endif()
